import type { Metadata } from "next";
import BiasAnalyzer from "./BiasAnalyzer";
import Comments from "@/app/components/Comments";
import PageHeader from "@/app/components/PageHeader";

export const metadata: Metadata = {
  title: "Media Bias Detector",
  description:
    "Paste in an article or transcript and get an AI-assisted, non-partisan read on its framing and where it sits on the political spectrum.",
};

export default function MediaBiasTrackerPage() {
  return (
    <div>
      <PageHeader
        title="Media Bias Detector"
        lede="Paste in an article or transcript from any outlet. It reads for loaded language and framing, then estimates where the piece sits on the political spectrum, so you can practice reading critically."
      />

      <section className="bg-paper-2">
        <div className="mx-auto max-w-6xl px-6 py-8">
          <p className="copy text-[0.9375rem]">
            <span className="font-semibold">Treat this as an estimate.</span>{" "}
            The analysis is generated by an AI model and can be wrong or miss
            context, and it isn&apos;t a fact-check. It&apos;s here to sharpen
            your own reading. Civics Studio endorses no outlet and no party.
          </p>
        </div>
      </section>

      <section className="bg-paper">
        <div className="mx-auto max-w-6xl px-6 py-16">
          <BiasAnalyzer />
        </div>
      </section>

      <Comments pageId="media-bias-tracker" />
    </div>
  );
}
