import type { Metadata } from "next";
import BiasAnalyzer from "./BiasAnalyzer";
import Comments from "@/app/components/Comments";

export const metadata: Metadata = {
  title: "Media Bias Detector",
  description:
    "Paste in an article or transcript and get an AI-assisted, non-partisan read on loaded language, framing, insinuation, and where the piece sits on the political spectrum.",
};

export default function MediaBiasTrackerPage() {
  return (
    <div className="bg-ink">
      <section className="border-b border-edge bg-panel">
        <div className="mx-auto max-w-5xl px-5 py-14 md:py-18">
          <p className="text-[10px] font-semibold uppercase tracking-[0.3em] text-maple lowercase">
            AI tool
          </p>

          <h1 className="serif mt-4 max-w-3xl text-5xl font-normal italic leading-tight tracking-[-0.02em] text-cream md:text-6xl lowercase">
            Media Bias Detector
          </h1>

          <p className="mt-5 max-w-2xl text-lg leading-8 text-mist">
            Paste in a news article, opinion piece, or transcript from any
            outlet. The tool reads for loaded language, framing choices,
            insinuation, and rhetorical technique, then estimates where the
            piece sits on the political spectrum, so you can practice reading
            critically, not just trust the byline.
          </p>

          <div className="mt-8 max-w-2xl border border-edge bg-ink p-5 text-sm leading-6 text-mist">
            <p className="mb-1 text-xs font-semibold uppercase tracking-[0.08em] text-cream">
              This is an estimate, not a verdict
            </p>
            The analysis is generated by an AI model and can be wrong,
            incomplete, or miss context. It&apos;s meant to sharpen your own
            media literacy, not to replace it, and it isn&apos;t a fact-check.
            Civics Studio doesn&apos;t endorse any outlet, party, or position.
          </div>
        </div>
      </section>

      <section className="bg-ink">
        <div className="mx-auto max-w-5xl px-5 py-12">
          <BiasAnalyzer />
        </div>
      </section>

      <Comments pageId="media-bias-tracker" />
    </div>
  );
}
